# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Mayoristas-Inaltum"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
client_id = "61ad9f74fe4602e05b8bdd0100af79de"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2027-01"

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
